name: destroy

on:
  workflow_dispatch:  # ręczne wywołanie

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.TF_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.TF_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf.hcl
        working-directory: .

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: .

      - name: Delete Lambda ZIPs from S3
        run: |
          aws s3 rm s3://$S3_BUCKET/authorizer_function.zip || true
          aws s3 rm s3://$S3_BUCKET/userfunction.zip || true
